/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import beans.DespesaUnidade;
import dao.DespesaUnidadeDAO;
import entities.enums.StatusPagamento;
import entities.enums.TipoDespesa;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Joacir
 */
public class EditarDespesa extends javax.swing.JFrame {

    /**
     * Creates new form EditarDespesa
     */
    public EditarDespesa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        boxTipoDespesa = new javax.swing.JComboBox<>();
        rodaValor = new javax.swing.JSpinner();
        txtDescricao = new javax.swing.JTextField();
        jDateVencimento = new com.toedter.calendar.JDateChooser();
        boxStatus = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnSalvarEditacao = new javax.swing.JButton();
        btnCancelarDespesa = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btnPesquisarId = new javax.swing.JButton();
        txtId = new javax.swing.JTextField();
        btnExcluirDespesa = new javax.swing.JButton();

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Valor");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Editar Despesa");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Tipo");

        boxTipoDespesa.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        boxTipoDespesa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AGUA", "LUZ", "INTERNET", "ALUGEL", "MANUTENCAO", "OUTROS" }));
        boxTipoDespesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxTipoDespesaActionPerformed(evt);
            }
        });

        rodaValor.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        txtDescricao.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescricaoActionPerformed(evt);
            }
        });

        jDateVencimento.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        boxStatus.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        boxStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PAGO", "PENDENTE", "VENCIDO" }));
        boxStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxStatusActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("Valor");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("Descricao");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("Vencimento");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setText("Status");

        btnSalvarEditacao.setBackground(new java.awt.Color(51, 255, 51));
        btnSalvarEditacao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSalvarEditacao.setText("Gravar");
        btnSalvarEditacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarEditacaoActionPerformed(evt);
            }
        });

        btnCancelarDespesa.setBackground(new java.awt.Color(255, 204, 204));
        btnCancelarDespesa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCancelarDespesa.setText("Voltar");
        btnCancelarDespesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarDespesaActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setText("Pesquisar Id");

        btnPesquisarId.setBackground(new java.awt.Color(204, 255, 255));
        btnPesquisarId.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnPesquisarId.setText("Pesquisar");
        btnPesquisarId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarIdActionPerformed(evt);
            }
        });

        txtId.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        btnExcluirDespesa.setBackground(new java.awt.Color(255, 0, 0));
        btnExcluirDespesa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnExcluirDespesa.setText("Excluir");
        btnExcluirDespesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirDespesaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDescricao)
                    .addComponent(boxStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDateVencimento, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                    .addComponent(boxTipoDespesa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rodaValor))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSalvarEditacao, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnExcluirDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelarDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPesquisarId)))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPesquisarId))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boxTipoDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rodaValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(jDateVencimento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvarEditacao)
                    .addComponent(btnCancelarDespesa)
                    .addComponent(btnExcluirDespesa))
                .addGap(12, 12, 12))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void boxTipoDespesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxTipoDespesaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxTipoDespesaActionPerformed

    private void boxStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxStatusActionPerformed

    private void btnSalvarEditacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarEditacaoActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(txtId.getText());
        TipoDespesa tipo = TipoDespesa.valueOf(boxTipoDespesa.getSelectedItem().toString());
        String strDescicao = txtDescricao.getText();
        double rValor = Double.parseDouble(rodaValor.getValue().toString());
        SimpleDateFormat dFormat = new SimpleDateFormat("yyyy-MM-dd");
        String date = dFormat.format(jDateVencimento.getDate());
        StatusPagamento status = StatusPagamento.valueOf(boxStatus.getSelectedItem().toString());

        DespesaUnidade despesaUnidade = new DespesaUnidade();
        despesaUnidade.setTipoDespesa(tipo);
        despesaUnidade.setDescricao(strDescicao);
        despesaUnidade.setValor(rValor);
        despesaUnidade.setVencimentoFatura(date);
        despesaUnidade.setStatusPagamento(status);

        DespesaUnidadeDAO despesaUnidadeDAO = new DespesaUnidadeDAO();
        despesaUnidadeDAO.editar(despesaUnidade, id);

        txtId.setText("");
        boxTipoDespesa.setSelectedItem("AGUA");
        txtDescricao.setText("");
        rodaValor.setValue(0);
        boxStatus.setSelectedItem("PAGO");
    }//GEN-LAST:event_btnSalvarEditacaoActionPerformed

    private void btnCancelarDespesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarDespesaActionPerformed
        // TODO add your handling code here:
        EditarDespesa.this.dispose();
    }//GEN-LAST:event_btnCancelarDespesaActionPerformed

    private void btnPesquisarIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarIdActionPerformed
        // TODO add your handling code here:
        int idPesquisa = Integer.parseInt(txtId.getText());
        DespesaUnidadeDAO despesaUnidadeDAO = new DespesaUnidadeDAO();
        DespesaUnidade despesaUnidade = despesaUnidadeDAO.getDespesa(idPesquisa);
        if(despesaUnidade == null) {
            JOptionPane.showMessageDialog(this, "Despesa não entrada");
        } else {
            // Preenche o form com os dados da despesa selecionada
            boxTipoDespesa.setSelectedItem(despesaUnidade.getTipoDespesa().toString());
            rodaValor.setValue(despesaUnidade.getValor());
            txtDescricao.setText(despesaUnidade.getDescricao());
            try {
                Date date = new SimpleDateFormat("yyyy-MM-dd").parse(despesaUnidade.getVencimentoFatura());
                jDateVencimento.setDate(date);
            } catch (ParseException ex) {
                Logger.getLogger(EditarDespesa.class.getName()).log(Level.SEVERE, null, ex);
            }
            boxStatus.setSelectedItem(despesaUnidade.getStatusPagamento().toString());
        }
    }//GEN-LAST:event_btnPesquisarIdActionPerformed

    private void btnExcluirDespesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirDespesaActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(txtId.getText());
        DespesaUnidadeDAO despesaUnidadeDAO = new DespesaUnidadeDAO();
        despesaUnidadeDAO.excluir(id);
        
        txtId.setText("");
        boxTipoDespesa.setSelectedItem("AGUA");
        txtDescricao.setText("");
        rodaValor.setValue(0);
        boxStatus.setSelectedItem("PAGO");
    }//GEN-LAST:event_btnExcluirDespesaActionPerformed

    private void txtDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescricaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarDespesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarDespesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarDespesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarDespesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarDespesa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxStatus;
    private javax.swing.JComboBox<String> boxTipoDespesa;
    private javax.swing.JButton btnCancelarDespesa;
    private javax.swing.JButton btnExcluirDespesa;
    private javax.swing.JButton btnPesquisarId;
    private javax.swing.JButton btnSalvarEditacao;
    private com.toedter.calendar.JDateChooser jDateVencimento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSpinner rodaValor;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtId;
    // End of variables declaration//GEN-END:variables
}
