/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import beans.Unidade;
import dao.UnidadeDAO;

/**
 *
 * @author Joacir
 */
public class FormUnidade extends javax.swing.JFrame {

    /**
     * Creates new form formUnidade
     */
    public FormUnidade() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        Proprietario = new javax.swing.JLabel();
        Identificacao = new javax.swing.JLabel();
        Condominio = new javax.swing.JLabel();
        Endereco = new javax.swing.JLabel();
        txtProprietario = new javax.swing.JTextField();
        txtIdentificacao = new javax.swing.JTextField();
        txtEndereco = new javax.swing.JTextField();
        txtCondominio = new javax.swing.JTextField();
        btnSalvarUnidade = new javax.swing.JButton();
        btnCancelarUnidade = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Titulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        Titulo.setText("Cadastro de Unidade");

        Proprietario.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Proprietario.setText("Proprietario");

        Identificacao.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Identificacao.setText("Identificação");

        Condominio.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Condominio.setText("Condomínio");

        Endereco.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Endereco.setText("Endereço");

        txtProprietario.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtProprietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProprietarioActionPerformed(evt);
            }
        });

        txtIdentificacao.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtIdentificacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdentificacaoActionPerformed(evt);
            }
        });

        txtEndereco.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnderecoActionPerformed(evt);
            }
        });

        txtCondominio.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtCondominio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCondominioActionPerformed(evt);
            }
        });

        btnSalvarUnidade.setBackground(new java.awt.Color(51, 255, 51));
        btnSalvarUnidade.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSalvarUnidade.setText("Salvar");
        btnSalvarUnidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarUnidadeActionPerformed(evt);
            }
        });

        btnCancelarUnidade.setBackground(new java.awt.Color(255, 0, 0));
        btnCancelarUnidade.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCancelarUnidade.setText("Voltar");
        btnCancelarUnidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarUnidadeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Proprietario)
                            .addComponent(Condominio)
                            .addComponent(Endereco))
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Identificacao)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdentificacao, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProprietario, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCondominio, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(183, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSalvarUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelarUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Titulo)
                        .addGap(168, 168, 168))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(Titulo)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Identificacao)
                    .addComponent(txtIdentificacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Proprietario)
                    .addComponent(txtProprietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Condominio)
                    .addComponent(txtCondominio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Endereco)
                    .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvarUnidade)
                    .addComponent(btnCancelarUnidade))
                .addGap(12, 12, 12))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtProprietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProprietarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProprietarioActionPerformed

    private void txtIdentificacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdentificacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdentificacaoActionPerformed

    private void txtEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnderecoActionPerformed

    private void txtCondominioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCondominioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCondominioActionPerformed

    private void btnSalvarUnidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarUnidadeActionPerformed
        // TODO add your handling code here:
        String strProprietario = txtProprietario.getText();
        String strIdentificacao = txtIdentificacao.getText();
        String strCondominio = txtCondominio.getText();
        String strEndereco = txtEndereco.getText();
        
        Unidade unidade = new Unidade();
        unidade.setIdentificacao(strIdentificacao);
        unidade.setProprietario(strProprietario);
        unidade.setCondominio(strCondominio);
        unidade.setEndereco(strEndereco);
        
        UnidadeDAO unidadeDAO = new UnidadeDAO();
        unidadeDAO.inserir(unidade);

        txtIdentificacao.setText("");
        txtProprietario.setText("");
        txtCondominio.setText("");
        txtEndereco.setText("");
    }//GEN-LAST:event_btnSalvarUnidadeActionPerformed

    private void btnCancelarUnidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarUnidadeActionPerformed
        // TODO add your handling code here:
        FormUnidade.this.dispose();
    }//GEN-LAST:event_btnCancelarUnidadeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormUnidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormUnidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormUnidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormUnidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormUnidade().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Condominio;
    private javax.swing.JLabel Endereco;
    private javax.swing.JLabel Identificacao;
    private javax.swing.JLabel Proprietario;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton btnCancelarUnidade;
    private javax.swing.JButton btnSalvarUnidade;
    private javax.swing.JTextField txtCondominio;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtIdentificacao;
    private javax.swing.JTextField txtProprietario;
    // End of variables declaration//GEN-END:variables
}
