/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import beans.Inquilino;
import dao.InquilinoDAO;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Joacir
 */
public class MostrarInquilino extends javax.swing.JFrame {

    // pega os dados das despesas de lista e joga dentro da tabela
    private void preencherTabela() {
        InquilinoDAO inquilinoDAO = new InquilinoDAO();
        List<Inquilino> listaInquilino = inquilinoDAO.getInquilino();
        
        DefaultTableModel tabelaInquilino = (DefaultTableModel) tblInquilino.getModel();
        
        // Percori a "listaDespesa" e inseri na tabelaDespesa
        for(Inquilino i : listaInquilino) {
            Object[] obj = new Object[] {
                i.getIdinquilino(),
                i.getNome(),
                i.getIdade(),
                i.getTelefone(),
                i.getEmail(),
                i.getSexo()
            };
            tabelaInquilino.addRow(obj);
        }
    }
    
    /**
     * Creates new form MostrarInquilino
     */
    public MostrarInquilino() {
        initComponents();
        preencherTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCancelarUnidade = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnEditarExcluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInquilino = new javax.swing.JTable();
        btnCancelarUnidade1 = new javax.swing.JButton();

        btnCancelarUnidade.setBackground(new java.awt.Color(255, 0, 0));
        btnCancelarUnidade.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCancelarUnidade.setText("Cancelar");
        btnCancelarUnidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarUnidadeActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Tabela de Inquilino");

        btnEditarExcluir.setBackground(new java.awt.Color(0, 153, 153));
        btnEditarExcluir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnEditarExcluir.setText("Editar/Excluir Inquilino");
        btnEditarExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarExcluirActionPerformed(evt);
            }
        });

        tblInquilino.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "idInquilino", "Nome", "Idade", "Telefone", "Email", "Sexo"
            }
        ));
        jScrollPane1.setViewportView(tblInquilino);

        btnCancelarUnidade1.setBackground(new java.awt.Color(255, 0, 0));
        btnCancelarUnidade1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCancelarUnidade1.setText("Voltar");
        btnCancelarUnidade1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarUnidade1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(188, 188, 188)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnEditarExcluir)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                        .addComponent(btnCancelarUnidade1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCancelarUnidade1)
                    .addComponent(btnEditarExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarExcluirActionPerformed
        // TODO add your handling code here:
        EditarInquilino frd = new EditarInquilino();
        frd.setVisible(true);
    }//GEN-LAST:event_btnEditarExcluirActionPerformed

    private void btnCancelarUnidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarUnidadeActionPerformed
        // TODO add your handling code here:
        MostrarInquilino.this.dispose();
    }//GEN-LAST:event_btnCancelarUnidadeActionPerformed

    private void btnCancelarUnidade1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarUnidade1ActionPerformed
        // TODO add your handling code here:
        MostrarInquilino.this.dispose();
    }//GEN-LAST:event_btnCancelarUnidade1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MostrarInquilino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MostrarInquilino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MostrarInquilino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MostrarInquilino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MostrarInquilino().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarUnidade;
    private javax.swing.JButton btnCancelarUnidade1;
    private javax.swing.JButton btnEditarExcluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblInquilino;
    // End of variables declaration//GEN-END:variables
}
