/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

/**
 *
 * @author Joacir
 */
public class PaginaInicial extends javax.swing.JFrame {

    /**
     * Creates new form PaginaInicial
     */
    public PaginaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnMostarUnidade = new javax.swing.JButton();
        btnCadastrarUnidade = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnMostarInquilino = new javax.swing.JButton();
        btnMostrarDespesas = new javax.swing.JButton();
        btnCadastrarInquilino = new javax.swing.JButton();
        btnCadastrarDespesa = new javax.swing.JButton();
        btnSairPrograma = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Titulo.setFont(new java.awt.Font("Segoe UI", 1, 44)); // NOI18N
        Titulo.setText("Página Inicial");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Unidade");

        btnMostarUnidade.setBackground(new java.awt.Color(255, 255, 51));
        btnMostarUnidade.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnMostarUnidade.setText("Mostrar");
        btnMostarUnidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostarUnidadeActionPerformed(evt);
            }
        });

        btnCadastrarUnidade.setBackground(new java.awt.Color(102, 255, 102));
        btnCadastrarUnidade.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnCadastrarUnidade.setText("Cadastrar");
        btnCadastrarUnidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarUnidadeActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Inquilino");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Despesa");

        btnMostarInquilino.setBackground(new java.awt.Color(255, 255, 51));
        btnMostarInquilino.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnMostarInquilino.setText("Mostrar");
        btnMostarInquilino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostarInquilinoActionPerformed(evt);
            }
        });

        btnMostrarDespesas.setBackground(new java.awt.Color(255, 255, 51));
        btnMostrarDespesas.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnMostrarDespesas.setText("Mostrar");
        btnMostrarDespesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarDespesasActionPerformed(evt);
            }
        });

        btnCadastrarInquilino.setBackground(new java.awt.Color(102, 255, 102));
        btnCadastrarInquilino.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnCadastrarInquilino.setText("Cadastrar");
        btnCadastrarInquilino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarInquilinoActionPerformed(evt);
            }
        });

        btnCadastrarDespesa.setBackground(new java.awt.Color(102, 255, 102));
        btnCadastrarDespesa.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnCadastrarDespesa.setText("Cadastrar");
        btnCadastrarDespesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarDespesaActionPerformed(evt);
            }
        });

        btnSairPrograma.setBackground(new java.awt.Color(255, 0, 0));
        btnSairPrograma.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        btnSairPrograma.setText("Sair do Programa");
        btnSairPrograma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairProgramaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addComponent(Titulo)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(121, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3))
                                .addGap(69, 69, 69)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnMostarInquilino)
                                    .addComponent(btnMostrarDespesas)
                                    .addComponent(btnMostarUnidade))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnCadastrarInquilino)
                                    .addComponent(btnCadastrarUnidade)
                                    .addComponent(btnCadastrarDespesa))))
                        .addGap(127, 127, 127))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSairPrograma)
                        .addGap(241, 241, 241))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulo)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMostarUnidade)
                    .addComponent(btnCadastrarUnidade)
                    .addComponent(jLabel1))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnMostarInquilino)
                    .addComponent(btnCadastrarInquilino))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(btnMostrarDespesas)
                    .addComponent(btnCadastrarDespesa))
                .addGap(29, 29, 29)
                .addComponent(btnSairPrograma)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarUnidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarUnidadeActionPerformed
        // TODO add your handling code here:
        FormUnidade frd = new FormUnidade();
        frd.setVisible(true);
    }//GEN-LAST:event_btnCadastrarUnidadeActionPerformed

    private void btnSairProgramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairProgramaActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSairProgramaActionPerformed

    private void btnMostrarDespesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarDespesasActionPerformed
        // TODO add your handling code here:
        MostrarDespesa frd = new MostrarDespesa();
        frd.setVisible(true);
    }//GEN-LAST:event_btnMostrarDespesasActionPerformed

    private void btnCadastrarDespesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarDespesaActionPerformed
        // TODO add your handling code here:
        FormDespesa frd = new FormDespesa();
        frd.setVisible(true);
    }//GEN-LAST:event_btnCadastrarDespesaActionPerformed

    private void btnMostarUnidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostarUnidadeActionPerformed
        // TODO add your handling code here:
        MostrarUnidade frd = new MostrarUnidade();
        frd.setVisible(true);
    }//GEN-LAST:event_btnMostarUnidadeActionPerformed

    private void btnMostarInquilinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostarInquilinoActionPerformed
        // TODO add your handling code here:
        MostrarInquilino frd = new MostrarInquilino();
        frd.setVisible(true);
    }//GEN-LAST:event_btnMostarInquilinoActionPerformed

    private void btnCadastrarInquilinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarInquilinoActionPerformed
        // TODO add your handling code here:
        FormInquilino frd = new FormInquilino();
        frd.setVisible(true);
    }//GEN-LAST:event_btnCadastrarInquilinoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaginaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaginaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaginaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaginaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaginaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton btnCadastrarDespesa;
    private javax.swing.JButton btnCadastrarInquilino;
    private javax.swing.JButton btnCadastrarUnidade;
    private javax.swing.JButton btnMostarInquilino;
    private javax.swing.JButton btnMostarUnidade;
    private javax.swing.JButton btnMostrarDespesas;
    private javax.swing.JButton btnSairPrograma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
